# Generated by Django 5.2 on 2025-05-06 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de categoría')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del juego')),
                ('precio_original', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio original')),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, help_text='Si no hay oferta, dejar vacío', max_digits=10, null=True, verbose_name='Precio con oferta')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('ruta_imagen', models.CharField(max_length=255, verbose_name='Ruta de imagen')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juegos', to='rest_api.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Juego',
                'verbose_name_plural': 'Juegos',
                'ordering': ['nombre'],
            },
        ),
    ]
